version: '3'
services:
  # mongo:
  #   image: mongo:3.6
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://172.17.0.1:27017/test 
    # links:
    #  - mongo 
    # depends_on: 
    #  - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     