version: '3'
networks:
  proxy:
    external:
      name: common_proxy
services:
  # mongo:
  #   image: mongo:3.6
  #   networks:
  #    - proxy
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://172.17.0.1:27017/test
    volumes:
     - .:/starter
     - /starter/node_modules
    networks:
     - proxy
  waf:
    build:
      context: waf
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - proxy
